version: '2'
services:

  # The Application
  app:
    env_file:
     - app/.env
    build:
      context: ./
      dockerfile: docker/app.dockerfile
    working_dir: /var/www
    volumes:
      - ./app:/var/www
  # The Web Server
  web:
    build:
      context: ./
      dockerfile: docker/web.dockerfile
    working_dir: /var/www
    volumes_from:
      - app
    ports:
      - 80:80
    depends_on:
      - app

   # The Database
  database:
    image: mysql:5.7
    volumes:
      - dbdata:/var/lib/mysql
      - ./docker/dump:/var/tmp/dump
    volumes_from:
      - app
    environment:
      - MYSQL_DATABASE=bagigisto
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - MYSQL_ROOT_PASSWORD=root
    ports:
        - "33061:3306"
  node:
    build:
      context: ./
      dockerfile: docker/node.dockerfile
    stdin_open: true
    working_dir: /var/www
    volumes_from:
      - app
    tty: true
#    command: npm run watch
    volumes:
     - ./app/:/var/www
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    links:
      - database

volumes:
  dbdata:
